@startuml
digraph dependencies {
 "libcurl4" -> "libzstd1"
 "libgcc-s1" -> "gcc-12-base"
 "libgssapi-krb5-2" -> "libkrb5-3"
 "librtmp1" -> "libnettle8"
 "libcurl4" -> "librtmp1"
 "libgssapi-krb5-2" -> "libc6"
 "libkrb5-3" -> "libc6"
 "libnettle8" -> "libc6"
 "libidn2-0" -> "libc6"
 "libsasl2-2" -> "libc6"
 "libzstd1" -> "libc6"
 "curl" -> "libc6"
 "libcurl4" -> "libpsl5"
 "libgnutls30" -> "libc6"
 "curl" -> "zlib1g"
 "libgnutls30" -> "libhogweed6"
 "librtmp1" -> "libgnutls30"
 "libcom-err2" -> "libc6"
 "libk5crypto3" -> "libc6"
 "librtmp1" -> "libc6"
 "librtmp1" -> "libhogweed6"
 "libpsl5" -> "libc6"
 "librtmp1" -> "zlib1g"
 "libgmp10" -> "libc6"
 "libkrb5-3" -> "libssl3"
 "libssl3" -> "<debconf-2.0>"
 "curl" -> "libcurl4"
 "libkrb5-3" -> "libkrb5support0"
 "libbrotli1" -> "libc6"
 "libgssapi-krb5-2" -> "libkrb5support0"
 "zlib1g" -> "libc6"
 "libssh-4" -> "zlib1g"
 "libcurl4" -> "libc6"
 "libgnutls30" -> "libidn2-0"
 "libcurl4" -> "zlib1g"
 "libssh-4" -> "libc6"
 "libk5crypto3" -> "libkrb5support0"
 "libpsl5" -> "libidn2-0"
 "libcurl4" -> "libgssapi-krb5-2"
 "libcurl4" -> "libnghttp2-14"
 "libhogweed6" -> "libgmp10"
 "libssh-4" -> "libgssapi-krb5-2"
 "libidn2-0" -> "libunistring2"
 "libgnutls30" -> "libp11-kit0"
 "libsasl2-2" -> "libsasl2-modules-db"
 "libcurl4" -> "libssl3"
 "libgnutls30" -> "libunistring2"
 "libssh-4" -> "libssl3"
 "libhogweed6" -> "libnettle8"
 "libcurl4" -> "libbrotli1"
 "libcurl4" -> "libidn2-0"
 "libpsl5" -> "libunistring2"
 "libgcc-s1" -> "libc6"
 "libkrb5support0" -> "libc6"
 "libc6" -> "libgcc-s1"
 "libcurl4" -> "libldap-2.5-0"
 "libssl3" -> "libc6"
 "libkrb5-3" -> "libcom-err2"
 "libldap-2.5-0" -> "libsasl2-2"
 "libgssapi-krb5-2" -> "libk5crypto3"
 "libkrb5-3" -> "libk5crypto3"
 "libnghttp2-14" -> "libc6"
 "libgssapi-krb5-2" -> "libcom-err2"
 "libcrypt1" -> "libc6"
 "libgnutls30" -> "libgmp10"
 "libc6" -> "libcrypt1"
 "libkrb5-3" -> "libkeyutils1"
 "libldap-2.5-0" -> "libgnutls30"
 "librtmp1" -> "libgmp10"
 "libhogweed6" -> "libc6"
 "libgnutls30" -> "libtasn1-6"
 "libldap-2.5-0" -> "libc6"
 "libunistring2" -> "libc6"
 "libgnutls30" -> "libnettle8"
 "libcurl4" -> "libssh-4"
}
@enduml
